### ISSUE TITLE
main_funktion mit Spielablauf

### ISSUE THREAD

**Issue by Nada2911** [Nada2911/viergewinnt#17]

**Comment by Nada2911** [comment]
Spieler nur einmal an der Reihe danach passiert nichts mehr.

**Comment by AlaskaRivendell** [comment]
Das Problem war, dass `gueltig = 0` außerhalb von `while weitermachen` definiert wurde und dann nicht mehr auf 0 zurückgesetzt, um in der nächsten Iteration `while gueltig == 0` zu triggern.

**Comment by AlaskaRivendell** [comment]
@Nada2911 
- [x] Textausgabe im Fall von Gewinn mit print()

**Comment by Nada2911** [comment]
Task erledigt.
