### ISSUE TITLE
Klasse Mensch

### ISSUE THREAD

**Issue by AlaskaRivendell** [Nada2911/viergewinnt#3]
- [x] abgeleitet von Spieler
- [x] __init__ mit super()
- [x] Methode ziehen() - nimmt einen Tastaturinput zwischen 1 und 7; Rückgabe: eingebener Wert als Zahl
- [x] getter/setter für Parameter Farbe implementieren, sodass die Farbe nur ein Character sein darf und X nicht als Farbe gewählt werden kann

**Comment by Nada2911** [comment]
Wie verwende ich die Input-Methode?

**Comment by AlaskaRivendell** [comment]
Mit input() kannst du eine Tatstatureingabe einlesen und diese auf einer Variable speichern.
Beispiel:
`x = input()`

**Comment by Nada2911** [comment]
Getter und Setter wurden in der Superklasse gesetzt.

**Comment by AlaskaRivendell** [comment]
Try - Except soll verhindern, dass ein Input gegeben wird der kein Integer ist.
