### ISSUE TITLE
Funktion spiel_konfigurieren()

### ISSUE THREAD

**Issue by AlaskaRivendell** [Nada2911/viergewinnt#8]
- [x] Fragt erst, ob zwei Menschen oder Mensch gegen Computer spielt.
- [x] Danach wird nach Name und Farbe der SpielerInnen gefragt.
- [x] Die jeweiligen Instanzen werden angelegt und als tuple[Spieler, Spieler] zurückgegeben.

**Comment by AlaskaRivendell** [comment]
Diese Funktion gehört nicht zu einer Klasse.

**Comment by Nada2911** [comment]
Tasks wurden erledigt.

**Comment by AlaskaRivendell** [comment]
Der Input zum Auswählen des Spielmodus' (S oder C) wurde nachträglich in eine while Schleife verpackt, die erst bei einem gültigen Input beendet wird.
